---
title: "Malinowski Review"
date: "10/6/2023"
categories:
  - Assignment5
---

In [Stephen Malinowski's visualization of Johann Sebastian Bach's "Great" Fugue in G minor, BWV 542,](https://www.youtube.com/watch?v=4WhPUqpaRp4&ab_channel=smalin) he uses a number of different features to visually bring the music to life. First, he illustrates the movement of the pitch to a higher or lower tone by placing boxes higher or lower on the screen, making it easy to see how the melody will flow. Each of these boxes corresponds in size to the duration of the note. He's animated it in such a way that the box seems to disappear within itself and then move to the next box (or note). The movement between boxes also illustrates how quickly one note changes to the next. Quick successions of notes seem to bounce across the screen whereas slower melodies move more gently.

Secondly, he utilizes different colors to represent different instruments. At any given moment, there are as many as four instruments playing at once and each has their own color for the boxes described above. They each have their own space on the page, in instruments being perceived as higher in tone generally staying in the top area of the screen. However, they do occasionally overlap when the notes they play are the same or lower/higher than that of their neighbor.

Altogether, these elements combine in such a way that feels as natural as simply listening to the piece. It feels almost as though the sounds have come to life in the form of colorful, bouncing boxes.
